run_modules:
  - custom_content

custom_data:
  strain_classification:
    section_name: 'Strain Classification'
    plot_type: 'table'
    id: 'strain_classification'
    pconfig:
      id: 'strain_classification'
      namespace: "strain classification"

  mapping_statistics:
    section_name: 'Mapping and Variant Statistics'
    plot_type: 'table'
    id: 'mapping_statistics'
    pconfig:
      id: 'mapping_statistics'
      namespace: "Mapping and Variant Statistics"

  groups:
    section_name: 'Sample Clustering Groups'
    plot_type: 'table'
    id: 'groups'
    pconfig:
      id: 'groups'
      namespace: "Sample Clustering Groups"
  
  distance_matrix:
    section_name: "Sample SNP distance"
    plot_type: 'heatmap'
    id: 'distance_matrix'
    pconfig:
      id: 'distance_matrix'
      namespace: 'Sample SNP distance'

sp:
  strain_classification:
    fn: "Strain_Classification.tab"
  mapping_statistics:
    fn: "Mapping_and_Variant_Statistics.tab"
  groups:
    fn: "*groups"
  distance_matrix:
    fn: "*_reorganized.matrix"

